name: calpal
description: A calendar chat app using Flutter AI Toolkit
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  dartantic_ai: ^0.9.0
  flutter:
    sdk: flutter
  # flutter_ai_providers: ^0.3.1
  flutter_ai_toolkit: ^0.9.1
  logging: ^1.3.0
  split_view: ^3.2.1

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
